# Generated by Django 2.2.6 on 2019-10-31 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linnk',
            new_name='Link',
        ),
    ]
