# Generated by Django 2.2.6 on 2019-11-06 21:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Contenido'),
        ),
    ]
